# Generated by Django 2.2.9 on 2020-02-28 12:24

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='curated_events',
            field=wagtail.core.fields.StreamField([('event_link', wagtail.core.blocks.URLBlock())], null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='curated_events_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='curated_events_title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='curated_events_title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='event_list_query',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='event_list_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='event_list_title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='event_list_title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='link_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='link_text_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='link_text_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='link_url_en',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='link_url_fi',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='link_url_sv',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='short_description_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='short_description_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
