# Generated by Django 2.2.9 on 2020-03-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200228_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='link_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='link_text_fi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='link_text_sv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='link_url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='link_url_fi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='link_url_sv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
