# Generated by Django 2.2.9 on 2020-03-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200316_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='social_media_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='social_media_description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='social_media_description_sv',
            field=models.TextField(null=True),
        ),
    ]
