# Generated by Django 2.2.9 on 2020-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200316_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='box_color',
            field=models.CharField(choices=[('COLOR_A', 'First Color'), ('COLOR_B', 'Second Color'), ('COLOR_C', 'Third Color'), ('COLOR_D', 'Fourth Color')], max_length=255, null=True),
        ),
    ]
