# Generated by Django 2.2.9 on 2020-03-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('application', '0006_collections_box_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_fi', models.CharField(max_length=255, null=True)),
                ('title_sv', models.CharField(max_length=255, null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_fi', models.TextField(null=True)),
                ('description_sv', models.TextField(null=True)),
                ('button_text_en', models.CharField(max_length=255, null=True)),
                ('button_text_fi', models.CharField(max_length=255, null=True)),
                ('button_text_sv', models.CharField(max_length=255, null=True)),
                ('button_url_en', models.URLField(null=True)),
                ('button_url_fi', models.URLField(null=True)),
                ('button_url_sv', models.URLField(null=True)),
                ('meta_information_en', models.TextField(null=True)),
                ('meta_information_fi', models.TextField(null=True)),
                ('meta_information_sv', models.TextField(null=True)),
                ('page_title_en', models.CharField(max_length=255, null=True)),
                ('page_title_fi', models.CharField(max_length=255, null=True)),
                ('page_title_sv', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Landing Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
