# Generated by Django 2.2.9 on 2020-04-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200403_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='box_color',
            field=models.CharField(choices=[('SUMU', 'Sumu'), ('ENGEL', 'Engel'), ('KUPARI', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='curated_events_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='curated_events_title_fi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='curated_events_title_sv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='event_list_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='event_list_title_fi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='event_list_title_sv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='social_media_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='social_media_description_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='social_media_description_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='subtitles_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='subtitles_fi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='subtitles_sv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='title_fi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='title_sv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
