# Generated by Django 2.2.9 on 2020-04-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200407_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='subtitles_en',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='subtitles_fi',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='subtitles_sv',
        ),
    ]
