# Generated by Django 2.2.9 on 2020-04-09 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0017_landingpagesfolder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandingPage',
            new_name='LandingPages',
        ),
    ]
