# Generated by Django 2.2.9 on 2020-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20200409_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='visible_on_frontpage',
            field=models.BooleanField(default=False),
        ),
    ]
