# Generated by Django 2.2.9 on 2020-04-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_collections_visible_on_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='visible_on_frontpage',
            field=models.BooleanField(default=False, verbose_name='Näytä kokoelma etusivulla'),
        ),
    ]
