# Generated by Django 2.2.9 on 2020-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_landingpages_visible_on_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='box_color',
            field=models.CharField(choices=[('FOG', 'Sumu'), ('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Taustaväri ylätunisteelle'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='link_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkki teksti EN'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='link_text_fi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkki teksti FI'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='link_text_sv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkki teksti SV'),
        ),
        migrations.AlterField(
            model_name='landingpages',
            name='page_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sivun otsikointi EN'),
        ),
        migrations.AlterField(
            model_name='landingpages',
            name='page_title_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Sivun otsikointi FI'),
        ),
        migrations.AlterField(
            model_name='landingpages',
            name='page_title_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Sivun otsikointi SV'),
        ),
    ]
