# Generated by Django 2.2.9 on 2020-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20200430_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Kuvaus EN'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_fi',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Kuvaus FI'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_sv',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Kuvaus SV'),
        ),
    ]
