# Generated by Django 2.2.9 on 2020-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20200505_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='description_en',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Kuvaus EN'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_fi',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Kuvaus FI'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_sv',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Kuvaus SV'),
        ),
    ]
