# Generated by Django 2.2.9 on 2020-06-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20200615_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpages',
            name='visible_on_frontpage',
        ),
    ]
