# Generated by Django 2.2.9 on 2020-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20200626_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpages',
            name='hero_background_image_color_en',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='hero_background_image_color_fi',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='hero_background_image_color_sv',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
    ]
