# Generated by Django 2.2.9 on 2020-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20200724_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='event_list_query_en',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Hakutulossivun www-osoite EN'),
        ),
        migrations.AddField(
            model_name='collections',
            name='event_list_query_fi',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Hakutulossivun www-osoite FI'),
        ),
        migrations.AddField(
            model_name='collections',
            name='event_list_query_sv',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Hakutulossivun www-osoite SV'),
        ),
    ]
