# Generated by Django 2.2.9 on 2020-07-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20200730_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='event_list_query',
        ),
    ]
