# Generated by Django 2.2.9 on 2020-08-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_remove_collections_event_list_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpages',
            name='description_color_en',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='description_color_fi',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='description_color_sv',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='title_color_en',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='title_color_fi',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='title_color_sv',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White')], max_length=255, null=True),
        ),
    ]
