# Generated by Django 2.2.9 on 2020-09-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20200831_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='photographer_credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
