# Generated by Django 2.2.9 on 2020-09-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_auto_20200922_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='box_color',
            field=models.CharField(choices=[('FOG', 'Sumu – vaaleansininen'), ('ENGEL', 'Engel – keltainen'), ('COPPER', 'Kupari – vihreä'), ('SUOMENLINNA', 'Suomenlinna – vaaleanpunainen')], max_length=255, null=True, verbose_name='Taustaväri ylätunnisteelle'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='curated_events_title_en',
            field=models.CharField(blank=True, default='Recommended events', max_length=255, null=True, verbose_name='Tapahtumien otsikko EN'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='curated_events_title_fi',
            field=models.CharField(blank=True, default='Suositellut tapahtumat', max_length=255, null=True, verbose_name='Tapahtumien otsikko FI'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='curated_events_title_sv',
            field=models.CharField(blank=True, default='Rekommenderade evenemang', max_length=255, null=True, verbose_name='Tapahtumien otsikko SV'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='event_list_title_en',
            field=models.CharField(blank=True, default='Related events', max_length=255, null=True, verbose_name='Tapahtumien otsikko EN'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='event_list_title_fi',
            field=models.CharField(blank=True, default='Sinua voisi myös kiinnostaa', max_length=255, null=True, verbose_name='Tapahtumien otsikko FI'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='event_list_title_sv',
            field=models.CharField(blank=True, default='Kolla även dessa', max_length=255, null=True, verbose_name='Tapahtumien otsikko SV'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='application.CustomImage', verbose_name='Kokoelman pääkuva'),
        ),
    ]
