# Generated by Django 2.2.9 on 2020-09-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_auto_20200922_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpages',
            name='description_color_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='description_color_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='description_color_sv',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='title_color_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='title_color_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='title_color_sv',
        ),
    ]
