# Generated by Django 2.2.9 on 2020-09-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_auto_20200924_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='photographer_credit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kuvaajan tiedot'),
        ),
    ]
