# Generated by Django 2.2.9 on 2020-09-24 09:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20200924_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content_section_en',
            field=wagtail.core.fields.RichTextField(verbose_name='Sisältöäalue EN'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content_section_fi',
            field=wagtail.core.fields.RichTextField(verbose_name='Sisältöäalue FI'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content_section_sv',
            field=wagtail.core.fields.RichTextField(verbose_name='Sisältöäalue SV'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='heading_section_en',
            field=wagtail.core.fields.RichTextField(verbose_name='Ingressi EN'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='heading_section_fi',
            field=wagtail.core.fields.RichTextField(verbose_name='Ingressi FI'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='heading_section_sv',
            field=wagtail.core.fields.RichTextField(verbose_name='Ingressi SV'),
        ),
        migrations.AlterField(
            model_name='accessibilitypage',
            name='content_section_en',
            field=wagtail.core.fields.RichTextField(verbose_name='Sisältöäalue EN'),
        ),
        migrations.AlterField(
            model_name='accessibilitypage',
            name='content_section_fi',
            field=wagtail.core.fields.RichTextField(verbose_name='Sisältöäalue FI'),
        ),
        migrations.AlterField(
            model_name='accessibilitypage',
            name='content_section_sv',
            field=wagtail.core.fields.RichTextField(verbose_name='Sisältöäalue SV'),
        ),
        migrations.AlterField(
            model_name='accessibilitypage',
            name='heading_section_en',
            field=wagtail.core.fields.RichTextField(verbose_name='Ingressi EN'),
        ),
        migrations.AlterField(
            model_name='accessibilitypage',
            name='heading_section_fi',
            field=wagtail.core.fields.RichTextField(verbose_name='Ingressi FI'),
        ),
        migrations.AlterField(
            model_name='accessibilitypage',
            name='heading_section_sv',
            field=wagtail.core.fields.RichTextField(verbose_name='Ingressi SV'),
        ),
    ]
