# Generated by Django 2.2.9 on 2020-09-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20200924_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpages',
            name='hero_background_image_color_en',
            field=models.CharField(blank=True, choices=[('FOG', 'Sumu'), ('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri EN'),
        ),
        migrations.AlterField(
            model_name='landingpages',
            name='hero_background_image_color_fi',
            field=models.CharField(blank=True, choices=[('FOG', 'Sumu'), ('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri FI'),
        ),
        migrations.AlterField(
            model_name='landingpages',
            name='hero_background_image_color_sv',
            field=models.CharField(blank=True, choices=[('FOG', 'Sumu'), ('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri SV'),
        ),
        migrations.AlterField(
            model_name='landingpages',
            name='hero_background_image_mobile_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='application.CustomImage', verbose_name='Pääkuva mobiililla EN'),
        ),
        migrations.AlterField(
            model_name='landingpages',
            name='hero_background_image_mobile_fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='application.CustomImage', verbose_name='Pääkuva mobiililla FI'),
        ),
        migrations.AlterField(
            model_name='landingpages',
            name='hero_background_image_mobile_sv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='application.CustomImage', verbose_name='Pääkuva mobiililla SV'),
        ),
    ]
