# Generated by Django 2.2.9 on 2020-10-14 14:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_auto_20200924_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='keywords_en',
            field=wagtail.core.fields.StreamField([('keywords_en', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords EN'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='keywords_fi',
            field=wagtail.core.fields.StreamField([('keywords_fi', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords FI'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='keywords_sv',
            field=wagtail.core.fields.StreamField([('keywords_sv', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords SV'),
        ),
        migrations.AddField(
            model_name='accessibilitypage',
            name='keywords_en',
            field=wagtail.core.fields.StreamField([('keywords_en', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords EN'),
        ),
        migrations.AddField(
            model_name='accessibilitypage',
            name='keywords_fi',
            field=wagtail.core.fields.StreamField([('keywords_fi', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords FI'),
        ),
        migrations.AddField(
            model_name='accessibilitypage',
            name='keywords_sv',
            field=wagtail.core.fields.StreamField([('keywords_sv', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords SV'),
        ),
        migrations.AddField(
            model_name='collections',
            name='keywords_en',
            field=wagtail.core.fields.StreamField([('keywords_en', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords EN'),
        ),
        migrations.AddField(
            model_name='collections',
            name='keywords_fi',
            field=wagtail.core.fields.StreamField([('keywords_fi', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords FI'),
        ),
        migrations.AddField(
            model_name='collections',
            name='keywords_sv',
            field=wagtail.core.fields.StreamField([('keywords_sv', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords SV'),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='keywords_en',
            field=wagtail.core.fields.StreamField([('keywords_en', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords EN'),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='keywords_fi',
            field=wagtail.core.fields.StreamField([('keywords_fi', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords FI'),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='keywords_sv',
            field=wagtail.core.fields.StreamField([('keywords_sv', wagtail.core.blocks.CharBlock())], blank=True, null=True, verbose_name='keywords SV'),
        ),
    ]
