# Generated by Django 2.2.9 on 2020-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_auto_20201102_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='course_list_query_en',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Course List Query EN'),
        ),
        migrations.AddField(
            model_name='collections',
            name='course_list_query_fi',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Course List Query FI'),
        ),
        migrations.AddField(
            model_name='collections',
            name='course_list_query_sv',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Course List Query SV'),
        ),
    ]
