# Generated by Django 2.2.9 on 2020-11-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('application', '0047_auto_20201102_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPagesFolder',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Banner Pages Folder',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='description_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='description_sv',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_color_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_color_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_color_sv',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_mobile_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_mobile_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_mobile_sv',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_background_image_sv',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_top_layer_image_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_top_layer_image_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='hero_top_layer_image_sv',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='social_media_image_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='social_media_image_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='social_media_image_sv',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='title_fi',
        ),
        migrations.RemoveField(
            model_name='landingpages',
            name='title_sv',
        ),
        migrations.CreateModel(
            name='BannerPages',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero_background_image_color_fi', models.CharField(blank=True, choices=[('FOG', 'Sumu'), ('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri FI')),
                ('hero_background_image_color_sv', models.CharField(blank=True, choices=[('FOG', 'Sumu'), ('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri SV')),
                ('hero_background_image_color_en', models.CharField(blank=True, choices=[('FOG', 'Sumu'), ('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri EN')),
                ('button_text_fi', models.CharField(max_length=255, null=True, verbose_name='Napin teksti FI')),
                ('button_text_sv', models.CharField(max_length=255, null=True, verbose_name='Napin teksti SV')),
                ('button_text_en', models.CharField(max_length=255, null=True, verbose_name='Napin teksti EN')),
                ('button_url_fi', models.URLField(max_length=500, null=True, verbose_name='Linkki suomenkieliselle sivulle')),
                ('button_url_sv', models.URLField(max_length=500, null=True, verbose_name='Linkki ruotsinkieliselle sivulle')),
                ('button_url_en', models.URLField(max_length=500, null=True, verbose_name='Linkki englanninkieliselle sivulle')),
                ('title_fi', models.CharField(max_length=255, null=True, verbose_name='Otsikko FI')),
                ('title_sv', models.CharField(max_length=255, null=True, verbose_name='Otsikko SV')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Otsikko EN')),
                ('description_fi', models.TextField(blank=True, null=True, verbose_name='Selite FI')),
                ('description_sv', models.TextField(blank=True, null=True, verbose_name='Selite SV')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Selite EN')),
                ('hero_background_image_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuva EN')),
                ('hero_background_image_fi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuva FI')),
                ('hero_background_image_mobile_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuva mobiililla EN')),
                ('hero_background_image_mobile_fi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuva mobiililla FI')),
                ('hero_background_image_mobile_sv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuva mobiililla SV')),
                ('hero_background_image_sv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuva SV')),
                ('hero_top_layer_image_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuvan päälle asettuva kuva EN')),
                ('hero_top_layer_image_fi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuvan päälle asettuva kuva FI')),
                ('hero_top_layer_image_sv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Pääkuvan päälle asettuva kuva SV')),
                ('social_media_image_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Some-postauksen kuva EN')),
                ('social_media_image_fi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Some-postauksen kuva FI')),
                ('social_media_image_sv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.CustomImage', verbose_name='Some-postauksen kuva SV')),
            ],
            options={
                'verbose_name': 'Banner',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='bottom_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.BannerPages', verbose_name='top banner'),
        ),
        migrations.AddField(
            model_name='landingpages',
            name='top_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='application.BannerPages', verbose_name='top banner'),
        ),
    ]
