# Generated by Django 2.2.9 on 2021-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_auto_20201222_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpages',
            name='hero_background_image_color_en',
            field=models.CharField(blank=True, choices=[('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri EN'),
        ),
        migrations.AlterField(
            model_name='bannerpages',
            name='hero_background_image_color_fi',
            field=models.CharField(blank=True, choices=[('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri FI'),
        ),
        migrations.AlterField(
            model_name='bannerpages',
            name='hero_background_image_color_sv',
            field=models.CharField(blank=True, choices=[('ENGEL', 'Engel'), ('COPPER', 'Kupari'), ('SUOMENLINNA', 'Suomenlinna')], max_length=255, null=True, verbose_name='Pääkuvan taustaväri SV'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='box_color',
            field=models.CharField(choices=[('ENGEL', 'Engel – keltainen'), ('COPPER', 'Kupari – vihreä'), ('SUOMENLINNA', 'Suomenlinna – vaaleanpunainen')], max_length=255, null=True, verbose_name='Taustaväri ylätunnisteelle'),
        ),
    ]
