# Generated by Django 2.2.9 on 2021-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_auto_20210305_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customimage',
            old_name='photographer_credit',
            new_name='photographer_credit_fi',
        ),
        migrations.AddField(
            model_name='customimage',
            name='photographer_credit_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Photographer credit'),
        ),
        migrations.AddField(
            model_name='customimage',
            name='photographer_credit_sv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fotografkredit'),
        ),
    ]
