# Generated by Django 2.2.9 on 2021-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_auto_20210308_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='description_en',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Kuvaus EN'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_fi',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Kuvaus FI'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='description_sv',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Kuvaus SV'),
        ),
    ]
