# Generated by Django 2.2.9 on 2021-05-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_increase_collection_desc_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='course_list_query_en',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='course_list_query_fi',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='course_list_query_sv',
        ),
    ]
