name: Build & Production
on:
  push:
    tags:
      - 'release-*'

# allow only one run at a time
concurrency: ${{ github.workflow }}

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
  K8S_REQUEST_CPU: 100m
  K8S_REQUEST_RAM: 300Mi
  K8S_LIMIT_CPU: 1000m
  K8S_LIMIT_RAM: 400Mi
  # horizontal pod autoscaler
  K8S_HPA_ENABLED: true
  K8S_HPA_MAX_REPLICAS: 8
  K8S_HPA_MIN_REPLICAS: 2
  K8S_HPA_MAX_CPU_AVG: 80 # 80% from request
#  K8S_HPA_MAX_RAM_AVG: 80 # 80% from request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2

  production:
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          K8S_ADDITIONAL_HOSTNAMES: ${{ secrets.K8S_ADDITIONAL_HOSTNAMES }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          K8S_SECRET_DEBUG: "false"
          K8S_SECRET_DJANGO_SECRET_KEY: ${{ secrets.GH_PRODUCTION_DJANGO_SECRET_KEY }}
          K8S_SECRET_SUPERUSER_PASSWORD: ${{ secrets.GH_PRODUCTION_SUPERUSER_PASSWORD }}
          K8S_SECRET_FRONTEND_BASE_URL: "https://tapahtumat.prod.kuva.hel.ninja"
          K8S_SECRET_DEFAULT_FILE_STORAGE: "storages.backends.azure_storage.AzureStorage"
          K8S_SECRET_AZURE_BUCKET_NAME: ${{ secrets.STABLE_AZURE_BUCKET_NAME }}
          K8S_SECRET_AZURE_BUCKET_CREDENTIALS: ${{ secrets.STABLE_AZURE_BUCKET_CREDENTIALS }}
          K8S_SECRET_AZURE_BUCKET_ACCOUNT_NAME: ${{ secrets.STABLE_AZURE_BUCKET_ACCOUNT_NAME }}
          K8S_SECRET_RESTORE_DB_DUMP: ${{ secrets.GH_RESTORE_DB_DUMP }}
          K8S_SECRET_RESTORE_DB_DUMP_MWH_CODE: ${{ secrets.GH_RESTORE_DB_DUMP_MWH_CODE }}
          K8S_SECRET_DATABASE_HOST: ${{ secrets.K8S_SECRET_DATABASE_HOST_STABLE }}
          K8S_SECRET_DATABASE_URL: ${{ secrets.K8S_SECRET_DATABASE_URL_STABLE }}
          K8S_SECRET_DATABASE_PORT: ${{ secrets.K8S_SECRET_DATABASE_PORT_STABLE }}
          K8S_SECRET_DATABASE_DB: ${{ secrets.K8S_SECRET_DATABASE_DB_STABLE }}
          K8S_SECRET_DATABASE_USERNAME: ${{ secrets.K8S_SECRET_DATABASE_USERNAME_STABLE }}
          K8S_SECRET_DATABASE_PASSWORD: ${{ secrets.K8S_SECRET_DATABASE_PASSWORD_STABLE }}

      - name: Deploy Publish Scheduled Pages Cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          secret_name: "project-events-helsinki-cms-secret"
          name: "publish-scheduled-pages"
          kubeconfig_raw: ${{ secrets.KUBECONFIG_RAW_STABLE}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: '* * * * *' # once per 1 minute
          command: "{/app/manage.py}"
          args: "{publish_scheduled_pages}"
